num1=int(input("Enter first number: "))
num2=int(input("Enter Second number: "))
print(f"Addtion of {num1} and {num2} is {num1+num2}")
print(f"Subtraction of {num1} and {num2} is {num1-num2}")
print(f"Multiplication of {num1} and {num2} is {num1*num2}")
print(f"Division of {num1} and {num2} is {num1/num2}")